name: SimplyVanish
main: asofold.simplyvanish.SimplyVanish
version: 0.1.3
commands:
  vanish: 
     description: no description available
  reappear:
     description: no description available
  vanished:
     description: no description available