name: SimplyVanish
main: asofold.simplyvanish.SimplyVanish
version: 0.2.1
commands:
  vanish: 
     description: no description available
  reappear:
     description: no description available
  vanished:
     description: no description available
  simplyvanish:
     description: no description available