name: SimplyVanish
main: me.asofold.simplyvanish.SimplyVanish
version: 0.4.0-PRE-5
commands:
  vanish: 
     description: 'Ensure you or another player is vanished (then: /vanish <player>).'
     aliases:
     - van
  reappear:
     description: 'Ensure you or another player is visible (then: /vanish <player>).'
     aliases:
     - rea
  tvanish: 
     description: 'Toggle your vanished state.'
     aliases:
     - vanisht
     - tvan
     - vant
  vanished:
     description: 'Show a list of vanished players.'
     aliases:
     - vand
  simplyvanish:
     description: '/simplyvanish ... for: reload | save | stats [reset] | flags | Otherwise same as vanflag.'
     aliases:
     - simvan
  vanflag:
     description: 'Set or display flags for yourself or others.'
     aliases:
     - flagvan
